import "~/styles/globals.css"

import type { Metadata } from "next"
import { Geist } from "next/font/google"

import { TRPCReactProvider } from "~/trpc/react"
import { auth } from "~/server/auth";
import { cookieToInitialState } from "wagmi";
import { wagmiConfig } from "~/components/auth/config";
import { headers } from "next/headers";
import AuthProvider from "~/components/auth/auth-provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }]
}

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans"
})

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const session = await auth()
  const wagmiState = cookieToInitialState(wagmiConfig, (await headers()).get("cookie"))

  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <AuthProvider session={session} wagmiState={wagmiState}>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
