import "~/styles/globals.css"

import type { Metadata } from "next"
import { Geist } from "next/font/google"

import { ClerkProvider } from "@clerk/nextjs"
import { QueryClientProvider } from "@tanstack/react-query"
import { ReactQueryDevtools } from "@tanstack/react-query-devtools"
import { Toaster } from "sonner"
import { TRPCReactProvider, queryClient } from "~/trpc/react"

const socialMedias = [
  {
    title: "Twitter / X",
    type: "x",
    href: "https://x.com/airanker_"
  }
]

export const metadata: Metadata = {
  title: "AIRanker",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }]
}

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans"
})

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geist.variable}`}>
        <body className={"flex h-screen w-full gap-12 flex-col"}>
          <QueryClientProvider client={queryClient}>
            <TRPCReactProvider>
              <ReactQueryDevtools initialIsOpen={false} />
              <Toaster />
              <div className={"flex-1 mx-auto w-full max-w-7xl px-4 xl:px-0"}>{children}</div>
            </TRPCReactProvider>
          </QueryClientProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
